//******************************************************************************
// $Header$
//
// The contents of this file are subject to the Flatland Public License 
// Version 1.1 (the "License"); you may not use this file except in 
// compliance with the License. You may obtain a copy of the License at 
// http://www.3dml.org/FPL/ 
//
// Software distributed under the License is distributed on an "AS IS" basis,
// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
// the specific language governing rights and limitations under the License. 
//
// The Original Code is Rover. 
//
// The Initial Developer of the Original Code is Flatland Online, Inc. 
// Portions created by Flatland are Copyright (C) 1998-2000 Flatland
// Online Inc. All Rights Reserved. 
//
// Contributor(s): Philip Stephens.
//******************************************************************************

// Tokens.

enum token {

	// No token.

	TOKEN_NONE = 0,

	// XML tokens.

	TOKEN_OPEN_TAG = 1,	
	TOKEN_CLOSE_TAG,
	TOKEN_OPEN_END_TAG,
	TOKEN_CLOSE_SINGLE_TAG,
	TOKEN_OPEN_COMMENT,	
	TOKEN_CLOSE_COMMENT,
	TOKEN_EQUAL,
	TOKEN_QUOTE,
	TOKEN_WHITESPACE,

	// Tag and parameter name tokens.

	TOKEN_ACTION = 10,
	TOKEN_ALIGN,
	TOKEN_AMBIENT_LIGHT,
	TOKEN_AMBIENT_SOUND,
	TOKEN_ANGLE,
	TOKEN_AREA,
	TOKEN_BLOCK,
	TOKEN_BLOCKSET,
	TOKEN_BODY,
	TOKEN_BRIGHTNESS,
	TOKEN_BSP_TREE,
	TOKEN_CACHE,
	TOKEN_CAMERA,
	TOKEN_COLOUR,
	TOKEN_COMMAND,
	TOKEN_CONE,
	TOKEN_COORDS,
	TOKEN_CREATE,
	TOKEN_DEBUG,
	TOKEN_DELAY,
	TOKEN_DIMENSIONS,
	TOKEN_DIRECTION,
	TOKEN_DOUBLE,
	TOKEN_ENTRANCE,
	TOKEN_EXIT,
	TOKEN_FACES,
	TOKEN_FILE,
	TOKEN_FLOOD,
	TOKEN_FRONT,
	TOKEN_GROUND,
	TOKEN_HEAD,
	TOKEN_HREF,
	TOKEN_ID,
	TOKEN_IMAGEMAP,
	TOKEN_LEVEL,
	TOKEN_LOAD,
	TOKEN_LOCATION,
	TOKEN_MAP,
	TOKEN_MOVABLE,
	TOKEN_NAME,
	TOKEN_NUMBER,
	TOKEN_ONLOAD,
	TOKEN_ORB,
	TOKEN_ORIENTATION,
	TOKEN_PARAM,
	TOKEN_PART,
	TOKEN_PARTS,
	TOKEN_PLACEHOLDER,
	TOKEN_PLACEMENT,
	TOKEN_PLAYBACK,
	TOKEN_PLAYER,
	TOKEN_POINT_LIGHT,
	TOKEN_POLYGON,
	TOKEN_POLYGONS,
	TOKEN_POPUP,
	TOKEN_POSITION,
	TOKEN_PROJECTION,
	TOKEN_RADIUS,
	TOKEN_REAR,
	TOKEN_RECT,
	TOKEN_REF,
	TOKEN_REPLACE,
	TOKEN_ROLLOFF,
	TOKEN_ROOT,
	TOKEN_RP,
	TOKEN_SCALE,
//	TOKEN_SET_STREAM,
	TOKEN_SHAPE,
	TOKEN_SIZE,
	TOKEN_SKY,
	TOKEN_SOLID,
	TOKEN__SOURCE,
	TOKEN_SOUND,
	TOKEN_SPEED,
	TOKEN_SPOT,
	TOKEN_SPOT_LIGHT,
	TOKEN_SPRITE,
	TOKEN_STREAM,
	TOKEN_STYLE,
	TOKEN_SYMBOL,
	TOKEN_SYNOPSIS,
	TOKEN_TARGET,
	TOKEN_TEXCOORDS,
	TOKEN_TEXT,
	TOKEN_TEXTALIGN,
	TOKEN_TEXTCOLOUR,
	TOKEN_TEXTURE,
	TOKEN_TITLE,
	TOKEN_TRANSLUCENCY,
	TOKEN_TRIGGER,
	TOKEN__TYPE,
	TOKEN_UPDATED,
	TOKEN_VELOCITY,
	TOKEN_VERSION,
	TOKEN_VERTEX,
	TOKEN_VERTICES,
	TOKEN_VOLUME,
	TOKEN_WMP,

	// Value type tokens.

	VALUE_ACTION_TRIGGER = 192,
	VALUE_ALIGNMENT,
	VALUE_BLOCK_REF,
	VALUE_BLOCK_TYPE,
	VALUE_BOOLEAN,
	VALUE_DEGREES,
	VALUE_DELAY_RANGE,
	VALUE_DIRECTION,
	VALUE_DIRRANGE,
	VALUE_DOUBLE_SYMBOL,
	VALUE_EXIT_TRIGGER,
	VALUE_FLOAT,
	VALUE_HEADING,
	VALUE_INTEGER,
	VALUE_MAP_COORDS,
	VALUE_MAP_DIMENSIONS,
	VALUE_MAP_SCALE,
	VALUE_MAP_STYLE,
	VALUE_NAME,
	VALUE_NAME_LIST,
	VALUE_ORIENTATION,
	VALUE_PCRANGE,
	VALUE_PERCENTAGE,
	VALUE_PLACEMENT,
	VALUE_PLAYBACK_MODE,
	VALUE_POINT_LIGHT_STYLE,
	VALUE_POPUP_TRIGGER,
	VALUE_PROJECTION,
	VALUE_RADIUS,
	VALUE_RECT,
	VALUE_REL_COORDS,
	VALUE_RGB,
	VALUE_SHAPE,
	VALUE_SINGLE_SYMBOL,
	VALUE_SIZE,
	VALUE_SPOT_LIGHT_STYLE,
	VALUE_SPRITE_SIZE,
//	VALUE_STREAM_COMMAND,
	VALUE_STRING,
	VALUE_SYMBOL,
	VALUE_TEXTURE_STYLE,
	VALUE_VALIGNMENT,
	VALUE_VERSION,
	VALUE_VERTEX_COORDS,

	// Unknown token.

	TOKEN_UNKNOWN = 255
};
